name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: yarn
      
      - name: Code style
        run: yarn lint
        continue-on-error: true
      
      - name: Code style fixes
        id: code-style-fixes
        if: failure()
        run: yarn lint:fix
        continue-on-error: true
      
      - name: Code style PR
        if: steps.code-style-fixes.conclusion != 'skipped'
        run: "echo TODO: implement"
      
      - name: Build
        run: yarn build
